"use strict";
exports.__esModule = true;
var express = require('express');
var router = express.Router();
var controllersUsers_1 = require("../controllers/controllersUsers");
router.post('/user', controllersUsers_1.usersRegister);
router.post('/userLogin', controllersUsers_1.loginUser);
router.post('/endUserLogin/:id', controllersUsers_1.endUserLogin);
router.get('/getCookie', controllersUsers_1.getCookie);
router.get('/show/:email', controllersUsers_1.getSurveys);
router.post('/add/:id', controllersUsers_1.scoreAdd);
module.exports = router;
