var express = require('express');
var morgan = require('morgan');
var app = express();
var port = process.env.PORT || 3000;
var cookieParser = require('cookie-parser');
var path = require('path');
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.static(path.join(__dirname, 'public/html')));
app.use(cookieParser());
app.use(express.json());
app.use(morgan('tiny'));
var userRoute = require('./routes/userRoute');
app.use('/user', userRoute);
var productRoute = require('./routes/productRoute');
app.use('/product', productRoute);
var storeRoute = require('./routes/storeRoute');
app.use('/store', storeRoute);
var cartRoute = require('./routes/cartRoute');
app.use('/cart', cartRoute);
app.listen(port, function () { return console.log('app Listening on port', port); });
