var express = require('express');
var router = express.Router();
var app = express();
var port = process.env.PORT || 3000;
app.use(express.static('public'));
var beachesRoute = require('./routes/beaches/routeBeaches');
var drinksRoute = require('./routes/drinks/routeDrinks');
app.use('/beaches', beachesRoute);
app.use('/drinks', drinksRoute);
app.listen(port, function () { return console.log('Server listen on port', port); });
module.exports = router;
